---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fluentd stack with ELB'


###############################################################################
### Parameters
###############################################################################
Parameters:
  KeyName:
    Description: Optional key pair of the ec2-user to establish a SSH connection.
    Type: String
    Default: ''
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Identifiant of the VPC
  SubnetsIds:
    Description: SubnetsIds of the autoscaling group
    Type: List<AWS::EC2::Subnet::Id>
  InstanceType:
    Description: 'Instance type'
    Type: String
    Default: 't2.nano'
  ElasticsearchUrl:
    Type: String
    Default: ''
    Description: Url of the Elasticsearch to send logs
  AWSsign:
    Type: String
    Default: 'false'
    Description: indicate if elasticsearch requests are signed or not
    AllowedValues:
    - true
    - false
  PrivateELB:
    Type: String
    Default: 'true'
    Description: indicate if ELB is only accessible into the VPC
    AllowedValues:
    - true
    - false
  BastionSecurityGroup:
    Type: String
    Default: 'sg-xxxxxxxx'
    Description: 'Security group of the bastion for SSH connection'
  CloudWatchLogsRetentionInDays:
    Description: 'The number of days log events are kept in CloudWatch Logs'
    Type: Number
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

###############################################################################
### Mappings
###############################################################################
Mappings:
  RegionMap:
    'ap-south-1':
      AMI: 'ami-9fc7b0f0'
    'eu-west-2':
      AMI: 'ami-bfe0eadb'
    'eu-west-1':
      AMI: 'ami-e5083683'
    'ap-northeast-2':
      AMI: 'ami-94bb6dfa'
    'ap-northeast-1':
      AMI: 'ami-9f0c67f8'
    'sa-east-1':
      AMI: 'ami-bb40d8d7'
    'ca-central-1':
      AMI: 'ami-eb20928f'
    'ap-southeast-1':
      AMI: 'ami-4dd6782e'
    'ap-southeast-2':
      AMI: 'ami-28cff44b'
    'eu-central-1':
      AMI: 'ami-af0fc0c0'
    'us-east-1':
      AMI: 'ami-9be6f38c'
    'us-east-2':
      AMI: 'ami-38cd975d'
    'us-west-1':
      AMI: 'ami-b73d6cd7'
    'us-west-2':
      AMI: 'ami-1e299d7e'


###############################################################################
### Conditions
###############################################################################
Conditions:
  isAWSSign: !Equals [!Ref AWSsign, 'true']
  hasBastion: !Not [!Equals [!Ref BastionSecurityGroup, 'sg-xxxxxxxx']]
  isPrivateELB: !Equals [!Ref PrivateELB, 'true']

###############################################################################
### Outputs
###############################################################################
Outputs:
  ElbSecurityGroup:
    Description: 'Security group for fluentd load balancer'
    Value: !Ref ElbSecurityGroup
  InstanceSecurityGroup:
    Description: 'Security group for fluentd intances'
    Value: !Ref InstanceSecurityGroup
  LoadBalancerDNSName:
    Description: Load Balancer DNS Name
    Value: !GetAtt [ LoadBalancer, DNSName ]
  AutoScalingGroupName:
    Description: AutoScaling Group Name which will manage creation of new EC2 Instances
    Value: !Ref AutoScalingGroup
  LaunchConfiguration:
    Description: Launch Configuration the AutoScalingGroup will use when creating new EC2 Instances
    Value: !Ref LaunchConfiguration

###############################################################################
### Resources
###############################################################################
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets: !Ref SubnetsIds
      Scheme: !If [isPrivateELB, internal, internet-facing]
      CrossZone: true
      Listeners:
      - LoadBalancerPort: 24224
        InstancePort: 24224
        Protocol: TCP
      SecurityGroups:
      - !Ref ElbSecurityGroup
      HealthCheck:
        Target: 'TCP:24224'
        HealthyThreshold: 2
        UnhealthyThreshold: 5
        Interval: 10
        Timeout: 5
      ConnectionSettings:
        IdleTimeout: 3600

  ElbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for fluentd
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 24224
          ToPort: 24224
          # Open into all private network. Change with sg id for more controle
          CidrIp: '0.0.0.0/0'
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: SG for fluentd loadbalancer

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for fluentd instances
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 24224
        ToPort: 24224
        SourceSecurityGroupId: !Ref ElbSecurityGroup
      - !If
        - hasBastion
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref BastionSecurityGroup
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: SG for fluentd instances

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
      - !Ref IAMRole

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: awslogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
              - 'logs:DescribeLogStreams'
              Resource:
              - !GetAtt [LogGroupFluentd, Arn]
        - !If
          - isAWSSign
          -
            PolicyName: 'Elasticsearch'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Effect: Allow
                Action:
                - "es:ESHttpGet"
                - "es:ESHttpHead"
                - "es:ESHttpPost"
                - "es:ESHttpPut"
                Resource:
                - '*'
          - !Ref 'AWS::NoValue'

  LogGroupFluentd:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref CloudWatchLogsRetentionInDays

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          default:
            !If
            - isAWSSign
            - [awslogs, fluentd-repo, fluentd-common, fluentd-config-aws, fluentd-service]
            - [awslogs, fluentd-repo, fluentd-common, fluentd-config, fluentd-service]

        awslogs:
          packages:
            yum:
              awslogs: []
          files:
            '/etc/awslogs/awscli.conf':
              content: !Sub |
                [default]
                region = ${AWS::Region}
                [plugins]
                cwlogs = cwlogs
              mode: '000644'
              owner: root
              group: root
            '/etc/awslogs/awslogs.conf':
              content: !Sub |
                [general]
                state_file = /var/lib/awslogs/agent-state
                [/var/log/messages]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/messages
                log_stream_name = {instance_id}/var/log/messages
                log_group_name = ${LogGroupFluentd}
                [/var/log/secure]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/secure
                log_stream_name = {instance_id}/var/log/secure
                log_group_name = ${LogGroupFluentd}
                [/var/log/cron]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/cron
                log_stream_name = {instance_id}/var/log/cron
                log_group_name = ${LogGroupFluentd}
                [/var/log/cloud-init.log]
                datetime_format = %b %d %H:%M:%S
                file = /var/log/cloud-init.log
                log_stream_name = {instance_id}/var/log/cloud-init.log
                log_group_name = ${LogGroupFluentd}
                [/var/log/cfn-init.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-init.log
                log_stream_name = {instance_id}/var/log/cfn-init.log
                log_group_name = ${LogGroupFluentd}
                [/var/log/cfn-hup.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-hup.log
                log_stream_name = {instance_id}/var/log/cfn-hup.log
                log_group_name = ${LogGroupFluentd}
                [/var/log/cfn-init-cmd.log]
                datetime_format = %Y-%m-%d %H:%M:%S
                file = /var/log/cfn-init-cmd.log
                log_stream_name = {instance_id}/var/log/cfn-init-cmd.log
                log_group_name = ${LogGroupFluentd}
                [/var/log/cloud-init-output.log]
                file = /var/log/cloud-init-output.log
                log_stream_name = {instance_id}/var/log/cloud-init-output.log
                log_group_name = ${LogGroupFluentd}
                [/var/log/dmesg]
                file = /var/log/dmesg
                log_stream_name = {instance_id}/var/log/dmesg
                log_group_name = ${LogGroupFluentd}
                [/var/log/td-agent]
                file = /var/log/td-agent/td-agent.log
                log_stream_name = {instance_id}/var/log/td-agent/td-agent.log
                log_group_name = ${LogGroupFluentd}
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              awslogs:
                enabled: true
                ensureRunning: true
                packages:
                  yum:
                  - awslogs
                files:
                - '/etc/awslogs/awslogs.conf'
                - '/etc/awslogs/awscli.conf'
        fluentd-repo:
          files:
            '/etc/yum.repos.d/td.repo':
              content: |
                [treasuredata]
                name=TreasureData
                baseurl=http://packages.treasuredata.com/2/redhat/\$releasever/\$basearch
                gpgcheck=1
                gpgkey=https://packages.treasuredata.com/GPG-KEY-td-agent
          commands:
            install_key:
              command: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent

        fluentd-config-aws:
          files:
            '/etc/td-agent/td-agent.conf':
              content: !Sub |
                <source>
                  type forward
                  port 24224
                  bind 0.0.0.0
                </source>

                <match *.*>
                  # For Elasticsearch aws service (sign V4)
                  type "aws-elasticsearch-service"
                  # Index prefix
                  logstash_prefix logsfluentd
                  logstash_format true
                  include_tag_key
                  request_timeout 15s
                  reconnect_on_error true
                  template_name logsfluentd-*
                  template_file /etc/td-agent/elasticsearch.template.conf

                  <endpoint>
                    url ${ElasticsearchUrl}
                    region ${AWS::Region}
                    # access_key_id "secret"
                    # secret_access_key "seekret"
                  </endpoint>

                  # buffering
                  buffer_type memory
                  flush_interval 30s
                  # Size of each chunk. A chunck contains many events
                  buffer_chunk_limit 5m
                  # Nb max of chunk in the queue
                  buffer_queue_limit 64
                  retry_wait 15s
                </match>

              mode: '000644'
              owner: root
              group: root
          commands:
            install_plugin_elasticsearch-aws:
              command: /usr/sbin/td-agent-gem install fluent-plugin-aws-elasticsearch-service

        fluentd-config:
          files:
            '/etc/td-agent/td-agent.conf':
              content: !Sub |
                <source>
                  type forward
                  port 24224
                  bind 0.0.0.0
                </source>


                <match *.*>
                  #type stdout

                  # https://github.com/uken/fluent-plugin-elasticsearch
                  type elasticsearch
                  hosts ${ElasticsearchUrl}

                  # Index prefix
                  logstash_prefix logsfluentd
                  logstash_format true
                  include_tag_key
                  request_timeout 15s
                  reconnect_on_error true
                  template_name logsfluentd-*
                  template_file /etc/td-agent/elasticsearch.template.conf

                  # buffering
                  buffer_type memory
                  flush_interval 30s
                  # Size of each chunk. A chunck contains many events
                  buffer_chunk_limit 10m
                  # Nb max of chunk in the queue
                  buffer_queue_limit 64
                  retry_wait 15s
                </match>

              mode: '000644'
              owner: root
              group: root
          commands:
            install_plugin_elasticsearch:
              command: /usr/sbin/td-agent-gem install fluent-plugin-elasticsearch

        fluentd-common:
          packages:
            yum:
              td-agent: []
          files:
            '/etc/td-agent/elasticsearch.template.conf':
              content: !Sub |
                {
                  "template": "logsfluentd-*",
                  "settings": {
                    "number_of_shards": 1,
                    "number_of_replicas": 0,
                    "index": {
                      "refresh_interval": "5s",
                      "query": { "default_field": "message" },
                      "routing": { "allocation.total_shards_per_node": 1 }
                    }
                  },
                  "mappings": {
                    "_default_": {
                      "_all": { "enabled": false, "omit_norms": true },
                      "_source": { "enabled": true },
                      "dynamic_templates": [
                        {
                          "string_fields": {
                            "match": "*",
                            "match_mapping_type": "string",
                            "mapping": {
                              "type": "string", "index": "analyzed", "omit_norms": true,
                              "fields": {
                                "raw": { "type": "keyword", "ignore_above": 256 }
                              }
                            }
                          }
                        }
                      ],
                      "properties": {
                        "@timestamp": { "type": "date", "index": "not_analyzed" },
                        "@version": { "type": "keyword" },
                        "message": { "type": "text" },
                        "severity": { "type": "keyword" },
                        "fields": {
                          "type": "object",
                          "dynamic": true
                        }
                      }
                    }
                  }
                }
              mode: '000644'
              owner: root
              group: root

        fluentd-service:
          services:
            sysvinit:
              td-agent:
                enabled: true
                ensureRunning: true
                packages:
                  - td-agent

    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum update -y
          yum install -y aws-cfn-bootstrap htop

          # Run cfn-init
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchConfiguration --region ${AWS::Region}


          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoScalingGroup --region ${AWS::Region}


  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 1
      HealthCheckType: ELB
      HealthCheckGracePeriod: 60
      LoadBalancerNames:
      - !Ref LoadBalancer
      Tags:
      - Key: Name
        Value: !Sub 'fluentd'
        PropagateAtLaunch: true
      VPCZoneIdentifier: !Ref SubnetsIds
      MetricsCollection:
      - Granularity: 1Minute
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        PauseTime: PT10M
        WaitOnResourceSignals: true
